name: flutter_start
description: A skeleton Flutter starting project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  go_router: ^6.0.5
  flutter_riverpod: ^2.1.3
  shared_preferences: ^2.0.17
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.2
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.1
  lint: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
